### ISSUE TITLE
Metric - Request List

### ISSUE THREAD

**Issue by leppott** [leppott/BioMonTools#3]
**Is your feature request related to a problem? Please describe.**
Want to be able to calculate any and all metrics for biological programs (bugs, fish, and algae).

**Describe the solution you'd like**
Add to this issue any metrics that are not in the package but want in the package.

**Describe alternatives you've considered**
NA

**Additional context**
Add here and will try to get in the package.

**Comment by leppott** [comment]
GA DNR

        - pi_Hydro2EPT
        - pi_Hydro2Trich
        - pi_Ortho2Chi
        - pi_Tanyp2Chi
        - pi_ChCr2Chi

https://github.com/leppott/BioMonTools/commit/8cb51d9b834e689dac572daba81c566f72974963

**Comment by leppott** [comment]
Added NCBI in v0.3.0.9019.

Missing Margalef and Gleason D.  (Have Simpson D).

**Comment by leppott** [comment]
Add as.numeric for TolVal2.

**Comment by leppott** [comment]
Add MA metrics and IBI thresholds.

Two regions (Central Hills and Western Highlands).

Email, 2019-06-26

**Comment by leppott** [comment]
Add estuary / marine metrics.

Might have to add a trigger metric type so will typically "exclude" est/mar metrics.

**Comment by leppott** [comment]
Add Gulf Biotic Index (2011) and MS Gulf Biotic Index (2013).

**Comment by leppott** [comment]
BCG, PacNW

BCG

- [ ] nt_BCG_att1
- [ ] pi_BCG_att1
- [ ] pt_BCG_att1

- [ ] nt_BCG_attNA
- [ ] pi_BCG_attNA
- [ ] pt_BCG_attNA

Habitat	Description (nt, pi, and pt)
BRAC	brackish
DEPO	depositional
GENE	generalist
HEAD	headwater
RHEO	rheophily
RIVE	riverine
SPEC	specialist
UNKN	unknown

**Comment by leppott** [comment]
nt, pt, pi - ET (Trichoptera,   and Ephemeroptera)
nt, pt, pi - EOT (Odonata,   Trichoptera, and Ephemeroptera)
nt, pt, pi - COTE (Coleoptera,   Odonata, Trichoptera, and Ephemeroptera)
% Individs Amphipoda + Isopoda

**Comment by leppott** [comment]
Changed EOT and COTE to OET and COET to match order of "POET".

**Comment by leppott** [comment]
Should be able to do fairly easily.  Give me a few days to work it into my schedule.

If you send me the scoring criteria for PA I can put that in the package as well.
(I have a copy of the WV SCI on my shelf that I can use for that index).

**Comment by calebtz** [comment]
That would be great - thank you! I will summarize both indices and will send them along asap, later today.

**Comment by leppott** [comment]
Added the metrics 

(1) number of taxa - tolerance value - intolerant ≤ 4, 
 nt_tv_intol4
 In the tolerance section of metrics.
 Also added pi_tv_intol4 and pt_tv_intol4
 
 (2) number of taxa - Orders Ephemeroptera, Plecoptera and Trichoptera (EPT) – tolerance value – intolerant ≤ 4, 
 nt_tv_intol4_EPT
 In the tolerance section of metrics
 
 (3) percent (0-100) of individuals - SubFamily Orthocladiinae, 
 pi_Ortho
 In the section with the other midge metrics
 
 (4) percent (0-100) of individuals - Family Chironomidae and Phylum Annelida. 
 pi_Chiro_Anne
 Put in the midge section of metrics
 
 Still have to go and document the metrics but they are in v0.4.0.9016
 
 Also need to QC them to ensure they are calculating correctly.

**Comment by calebtz** [comment]
Thank you. I think the best way to maybe be helpful is to direct you to the sources for the [PA IBI](http://files.dep.state.pa.us/Water/Drinking%20Water%20and%20Facility%20Regulation/WaterQualityPortalFiles/Technical%20Documentation/freestoneIBImarch2012.pdf) (Appendix C and D??) and  WV [GLIMPSS/GLIMPSS(CF)](https://dep.wv.gov/WWE/watershed/bio_fish/Documents/20110829GLIMPSSFinalWVDEPDOI.pdf). Each index has multiple strata w/different scoring criteria for each - they're complex enough that I think you'd want to look at the source documents, if you want to do the work to incorporate them. Thanks again.

**Comment by calebtz** [comment]
Slight issue (typo) with metric name for "number of taxa - Orders Ephemeroptera, Plecoptera and Trichoptera (EPT) – tolerance value – intolerant ≤ 4". "nt_tv_intol4_EPT" (stated earlier) didn't run, so I checked and it's "nt_intol4_EPT". Not sure which is preferred, just letting you know of discrepancy.

**Comment by leppott** [comment]
Getting there on putting in PA freestone IBI.  Need to add in a new Becks index as well.

**Comment by leppott** [comment]
PA DEP Freestone IBI working using example data from report.

![image](https://user-images.githubusercontent.com/24276278/85722684-8932b800-b6c0-11ea-903b-c848455477d9.png)

![image](https://user-images.githubusercontent.com/24276278/85722739-9780d400-b6c0-11ea-8326-1111c415098a.png)

**Comment by calebtz** [comment]
Thank you, this is incredibly helpful! I look forward to using it in the next few days and will let you know if I run into any issues.

**Comment by leppott** [comment]
WV GLIMPSS metrics and index scoring are in a development version.  Will post after QC and get test running with example data from GLIMPSS report Tables D-1 and D-2.

**Comment by calebtz** [comment]
Excellent, thank you. I was hesitant to ask, but this well be very helpful!

Caleb Tzilkowski, PhD
Aquatic Ecologist
Eastern Rivers and Mountains Network
National Park Service
426 Forest Resources Building
University Park, PA 16802
(267) 990-5078
http://nps.gov/im/ermn
________________________________

**Comment by leppott** [comment]
WV GLIMPSS is done.

Notes:
1. No raw data to metric values examples.
2. Table D-1, West Fork Pond Fork, 100% QC
3. Table D-2, Bear Fork, the report has calculation errors.
4.  There are 4 narrative categories but only the two lowest (Degraded and Severely Degraded) are given in the report.
5. Added all regions (n=7) but not the midge genus (CF) indices.

WV report Table D-2 is incorrect for 3 metrics.
x_HBI,       (6.64-3.6)/(6.64-2.49) * 100  = 73.25301 # Reported as 73.2
%EPTNoCheu,  (86.2-2.5)/(90.8-2.5) * 100   = 94.79049 # Reported as 94.7
%Chiro+Anne, (84.7-9.9) / (84.7-1.8) * 100 = 90.22919 # Reported as 90.1
Overall Sum is off but report has the correct value for the average value.

Added 2 highest narrative categories as "Non-Degraded" and "Exceptional".

![image](https://user-images.githubusercontent.com/24276278/86589601-ef8ac680-bf5b-11ea-9186-70abcffc1a96.png)

![image](https://user-images.githubusercontent.com/24276278/86589643-06311d80-bf5c-11ea-82b1-dc67b141e9e4.png)

![image](https://user-images.githubusercontent.com/24276278/86589550-dc77f680-bf5b-11ea-9281-93dd5aac3256.png)

![image](https://user-images.githubusercontent.com/24276278/86589465-bd796480-bf5b-11ea-80b0-0ec038b15e35.png)

![image](https://user-images.githubusercontent.com/24276278/86589495-ca965380-bf5b-11ea-8391-56d4e82f7156.png)

**Comment by leppott** [comment]
Add % individuals Isoptera, Gastropoda, and Hirudinea for MI.

**Comment by leppott** [comment]
nt, pt, and pi


FFG | MH | Macrophyte herbivore
-- | -- | --
FFG | XY | Xylophage (wood eater)
FFG | PH | Piercer-herbivore
  |   |  
  |   |  
FFG | nt_ffg_mh | number of taxa - Functional   Feeding Group (FFG) - macrophyte herbivore (MH)
FFG | pi_ffg_mh | percent individuals - Functional   Feeding Group (FFG) - macrophyte herbivore (MH)
FFG | pt_ffg_mh | percent taxa - Functional   Feeding Group (FFG) - macrophyte herbivore (MH)
  |   |  
FFG | nt_ffg_xy | number of taxa - Functional   Feeding Group (FFG) - xylophage (wood eater) (XY)
FFG | pi_ffg_xy | percent individuals - Functional   Feeding Group (FFG) - xylophage (wood eater) (XY)
FFG | pt_ffg_xy | percent taxa - Functional   Feeding Group (FFG) - xylophage (wood eater) (XY)
  |   |  
FFG | nt_ffg_ph | number of taxa - Functional   Feeding Group (FFG) - piercer-herbivore (PH)
FFG | pi_ffg_ph | percent individuals - Functional   Feeding Group (FFG) - piercer-herbivore (PH)
FFG | pt_ffg_ph | percent taxa - Functional   Feeding Group (FFG) - piercer-herbivore (PH)

GENE: % by abundance
RHEO: % by abundance
Other (all other categories): % by abundance
GENE: % by taxa
RHEO: % by taxa

**Comment by leppott** [comment]
Closing ticket.  Will create a new ticket for each set of metrics to add to the package.
