### ISSUE TITLE
pi_EPT accidentally removes Family Cheumatopsyche

### ISSUE THREAD

**Issue by Blocktt** [leppott/BioMonTools#41]
pi_EPT accidentally removes Family Cheumatopsyche: 

pi_EPT = 100*sum(N_TAXA[ORDER == "Ephemeroptera" |
                                     ORDER == "Trichoptera" | ORDER == "Plecoptera" &
                                       (is.na(FAMILY)==TRUE | FAMILY != "Cheumatopsyche")], na.rm=TRUE)/ni_total
I will change on my end but I just wanted to bring this up as you may wonder why I made the change!
https://github.com/leppott/BioMonTools/blob/5539f4a3c1fc2a37ee23363e4d2964204ecd91ee/R/metric.values.R#L796

**Comment by leppott** [comment]
When creating new metric "pi_EPTNoCheu" messed up the naming with "pi_EPT". 

Issue #3 , WV GLIMPSS
v0.4.0.9019
https://github.com/leppott/BioMonTools/commit/b5b45d88123414d9320e73fe1db301d039ce790f
