### ISSUE TITLE
Metric Value Output - Excel, group by worksheet

### ISSUE THREAD

**Issue by leppott** [leppott/BioMonTools#68]
**Is your feature request related to a problem? Please describe.**
Create Excel output of metric.values() with metrics groups on different worksheets.

**Describe the solution you'd like**
File too wide for Access and some users find hard to find metrics.  Split into different worksheets.

**Describe alternatives you've considered**

**Additional context**
Use MetricNames file to define groups.

Include as a new function so can use in R console and Shiny.  For Shiny include in output for metric.values().

**Comment by leppott** [comment]
Writexl should be fine for multiple sheets.

https://stackoverflow.com/questions/62436524/how-to-use-librarywritexl-pakcage-to-save-multiple-dataframe-with-a-custmized

Have to use a list.  

Don't need anything fancy for the formatting.
```
write_xlsx(list("sh_1" = myTable, "sh2" = myTable), path = "test.xlsx")
```

**Comment by HedinTT** [comment]
Hey Erik,

Can I pick your brain on this for a minute? I’ve got everything listed out just fine but for the life of me I can’t get this multiple sheets thing to work.

Call me if you have time, thanks!!!!

**Comment by leppott** [comment]
metvalgrpxl()
