### ISSUE TITLE
Add metrics for NM BCG

### ISSUE THREAD

**Issue by Blocktt** [leppott/BioMonTools#97]
Add bug and fish metrics for NM BCG.
Bug metrics needed include:
- nt_TrichNoHydro
- pt_TrichNoHydro
- nt_Mol_nonatt6
- ni_total_300

Fish metrics needed include:
- pi_BCG_att1234
- nt_LLNLB
- nt_Cyprinidae_BCG_att1234
- nt_Hybognathus_amarus
- nt_Broadcast
- x_TrophicCats
- pi_BCG_attnon6
- nt_piscivore_BCG_attnon6

**Comment by leppott** [comment]
Did edits by hand instead of merge (too many conflicts).

https://github.com/leppott/BioMonTools/commit/e6b589fb10fffab7b6c92b2ba1da7787a879f2bd
